### ISSUE TITLE
Error when running Streaming Avatar Demo

### ISSUE THREAD

**Issue by mkhuthir** [HeyGen-Official/StreamingAvatar#8]
I have Ubuntu Linux 22.04 LTS with npm 8.5.1 and getting the following error when trying to run the demo:

xxx@xxxDT2:~/Downloads/StreamingAvatar$ node server.js
/home/xxx/Downloads/StreamingAvatar/node_modules/openai/index.js:50
    constructor({ baseURL = Core.readEnv('OPENAI_BASE_URL'), apiKey = Core.readEnv('OPENAI_API_KEY'), organization = Core.readEnv('OPENAI_ORG_ID') ?? null, ...opts } = {}) {
                                                                                                                                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/mkhuthir/Downloads/StreamingAvatar/server.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

xxx@xxxDT2:~/Downloads/StreamingAvatar$ npm -v
8.5.1

can you please guide me on what is missing ?

**Comment by mkhuthir** [comment]
I was able to resolve issue by updating node version. using the following commands:

```
sudo npm install n -g
n latest
node -v
```
